CREATE DATABASE SALES;
CREATE DATABASE SCHOOL;
USE SALES;
CREATE TABLE CUSTOMERS(C_ID INT PRIMARY KEY,C_NAME VARCHAR(50),EMAIL VARCHAR(50),CITY VARCHAR(20), segment varchar(30));
CREATE TABLE PRODUCTS (PRODUCT_ID INT PRIMARY KEY,PRODUCT_NAME VARCHAR(50),CATEGORY VARCHAR(30),PRICE DECIMAL(10,2));
CREATE TABLE ORDERS(O_ID INT PRIMARY KEY,C_ID INT,O_DATE DATE, FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID));
INSERT INTO CUSTOMERS
VALUES(1,"SHANTHI","CHSHANTHI122@GMAIL.COM","HYDERABAD","HOME OFFICE"),
	  (2,"SRIJA","SRIJA122@GMAIL.COM","BENGALURU","CORPORATE"),
      (3,"CHADANA","CHANDU122@GMAIL.COM","CHENNAI","CONSUMER"),
      (4,"ASHU","ASHU122@GMAIL.COM","MUMBAI","HOME OFFICE"),
      (5,"THAISEENA","THAISEENA122@GMAIL.COM","KHAMMAM","CONSUMER");
INSERT INTO PRODUCTS
VALUES(101,"LAPTOP","ELECTRONICS",55000),
	  (102,"MOBILE","ELECTRONICS",20000),
      (103,"HEADPHONES","ACCESSORIES",2200),
      (104,"KEYBOARD","ACCESSORIES",1500),
      (105,"MONITOR","ELECTRONICS",12000);

INSERT INTO ORDERS 
VALUES(101, 1, '2025-01-10'),
      (102, 2, '2025-01-12'),
      (103, 1, '2025-01-15'),
      (104, 3, '2025-01-20'),
      (105, 4, '2025-01-22');
-- select desired columns
SELECT C_ID, C_NAME,EMAIL 
FROM CUSTOMERS;

-- PERMANENTLY DELETE DATABASE
DROP DATABASE SCHOOL;
-- Update single value by primary key reference
UPDATE CUSTOMERS
SET EMAIL="MADASTUSRIJA122@GMAIL.COM"
WHERE C_ID=2;
SELECT *
FROM CUSTOMERS;
-- SHOW ALL THE DATABSES IN THE SYSTEM
show DATABASES;

-- SHOW ALL THE TABLES IN A SELECTED DATABASE
SHOW TABLES;

/*
CATEGORIES OF COMMANDS:
=======================
DDL (DATA DEFINITION LANGUAGE) - SCHEMA, CREATE (data types, constraints), ALTER (rename/add/drop), DROP, TRUNCATE
DML (DATA MANIPULATION LANGUAGE) - INSERT, UPDATE, DELETE, STORED PROCEDURE
DQL (DATA QUERY LANGUAGE) - SELECT, CLAUSES (where, group by, having, order by, top, offset, fetch), JOINS(inner, left, right, full, cross, self), UNION, UNION ALL
DCL (DATA CONTROL LANGUAGE)-REVOKE , GRANT
TCL (TRANSACTION CONTROL LANGUAGE)- COMMIT,ROLLLBACK,SAVEPOINT
*/
-- ALL RECORDS WITH SINGLE CONDITION
SELECT * FROM orders
WHERE O_DATE = '2025-01-10';

-- ALL RECORDS WITH MULTIPLE CONDITIONS (in same column)
SELECT * FROM CUSTOMERS
WHERE CITY IN('HYDERABAD', 'CHENNAI');

-- ALL RECORDS WITH MULTIPLE CONDITIONS (in different columns)
SELECT CATEGORY, PRODUCT_NAME, PRICE FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS' OR (PRODUCT_NAME = 'MOBILE' AND PRICE > 10000);

SELECT * FROM PRODUCTS
WHERE PRICE > 15000;
-- customers names in ascending order
SELECT * FROM customers
ORDER BY c_name DESC;
-- CITY IN DESCENDING ORDER FOR C_NAME 'ASHU'
SELECT * FROM CUSTOMERS
WHERE C_NAME = 'ASHU'
ORDER BY CITY DESC;

SELECT *FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 3;

SELECT *FROM PRODUCTS
LIMIT 3,2;
-- 2nd highest
SELECT * FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 1,1; 
-- ---------- WILDCARD : %  _  -----------
-- Names starting with 'S'
SELECT * FROM CUSTOMERS
WHERE C_NAME LIKE 'S%';

-- Names with exactly 5 characters
SELECT * FROM CUSTOMERS
WHERE C_NAME LIKE '_____';

SELECT * FROM CUSTOMERS
WHERE C_NAME LIKE '%r%';

SELECT * FROM CUSTOMERS
WHERE C_NAME LIKE '__a%';

-- -----------AGGREGATE FUNCTIONS------------
-- COUNT
-- SUM
-- MIN
-- MAX 
-- AVERAGE
SELECT COUNT(C_NAME) CUSTOMERS_COUNT
FROM CUSTOMERS;

SET SQL_SAFE_UPDATES=0;

UPDATE PRODUCTS
SET PRODUCT_NAME = 'LAPTOP'
WHERE PRODUCT_NAME = 'KEYBOARD';

SELECT PRODUCT_NAME,COUNT(DISTINCT(CATEGORY)) AS UNIQUE_CATEGORY
FROM PRODUCTS
GROUP BY PRODUCT_NAME;

 SELECT SUM(price) AS TOTAL_PRICE
    FROM PRODUCTS;
    
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCTS;

SELECT MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS;

select round(avg(price),2) as average_price
from products;
-- 2nd highest price
select max(price)
from products
where price<(select max(price) from products);
-- -----------------------------------------------------
-- CASE -- USES MULTIPLE CONDITIONS WITH LOGIC
SELECT PRODUCT_NAME,PRICE,
CASE
    WHEN PRICE>=60000 THEN 'COSTLY'
    WHEN PRICE>=20000 THEN 'MODERATE'
    WHEN PRICE >=1300 THEN 'NORMAL'
    ELSE 'CHEAP'
END AS RESULT
FROM PRODUCTS;

-- ------------------------JOINS --------------------------------------
-- USED TO COMBINE ROWS FROM 2 OR MORE TABLES BASED ON RELATED COLUMN BETWEEN THEM
/*INNER JOIN (join)                 -- exact matching records
 LEFT JOIN (left outer join)       -- all records from left table and matched record from right table
 RIGHT JOIN (right outer join)     -- all records from right table and matched record from left table
 FULL JOIN (full outer join)       -- all records from both tables
 CROSS JOIN                        -- all rows from left table display with all rows from right table
 SELF JOIN                         -- joins with itself
 -------------------
 Joins the queries
 -------------------
 UNION            -- aloow unique values only
 UNION ALL        -- allow duplicates as well
*/
-- inner join
select c.c_id,c.c_name,o.o_id,o.o_date 
from customers c
inner join orders as o
on c.c_id=o.c_id;

-- left join 
SELECT C.C_ID, C.C_NAME, O.O_ID, O.O_DATE
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.C_ID = O.C_ID;
-- Customers Who Did NOT Place Any Orders
SELECT C.C_ID, C.C_NAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.C_ID = O.C_ID
WHERE O.C_ID IS NULL;
-- Count Orders Per Customer
SELECT C.C_ID, C.C_NAME, COUNT(O.O_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.C_ID = O.C_ID
GROUP BY C.C_ID, C.C_NAME;

-- right join
SELECT C.C_ID, C.C_NAME, O.O_ID, O.O_DATE
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.C_ID = O.C_ID;

-- ------------------- UNION, UNION ALL(Joins two QUERIES) --------------------

-- NUMBER OF COLUMNS MUST BE SAME
-- DATA TYPES MUST BE SAME
-- DATA INFORMATION SHOULD BE SAME

select c_id from customers
union
select c_id from orders;

select c_id from customers
union all
select c_id from orders;

-- ----------- RANKING FUCNTIONS ------------------
-- ROW_NUMBER() --ASSIGNS UNIQUE SEQUENCE NUMBER TO EACH ROW 
select PRODUCT_NAME,PRICE,
ROW_NUMBER() OVER (ORDER BY PRICE DESC) AS RN
FROM PRODUCTS;
-- RANK() Assigns the same rank for equal values, but skips numbers after ties.
SELECT PRODUCT_NAME,PRICE,
RANK() OVER (ORDER BY PRICE DESC) AS RANK_NO
FROM PRODUCTS;
-- DENSE_RANK() Same as RANK(), but no gaps after ties.
SELECT PRODUCT_NAME, PRICE,
DENSE_RANK() OVER (ORDER BY PRICE DESC) AS DENSE_RANK_NO
FROM PRODUCTS;

-- NTILE(n)Divides rows into given number of groups(buckets)
SELECT PRODUCT_NAME, PRICE,
NTILE(3) OVER (ORDER BY PRICE DESC) AS BUCKET
FROM PRODUCTS;

-- ------------- CTE (COMMON TABLE EXPRESSION) + WINDOWS FUNCTION -------------
-- TO SEE THE DESIRED RANKING (nth Rank) POSITION ONLY
-- 2nd highest priced product
WITH RankedProducts AS (
SELECT PRODUCT_NAME, PRICE,
DENSE_RANK() OVER (ORDER BY PRICE DESC) AS RNK
FROM PRODUCTS
)
SELECT *
FROM RankedProducts
WHERE RNK = 2;

-- STORED PROCEDURE

DELIMITER $$

CREATE PROCEDURE SEGMENT_ORDER_DETAIL()
BEGIN
    SELECT C.SEGMENT, COUNT(O.O_ID) AS TOTAL_ORDERS
    FROM CUSTOMERS C
    JOIN ORDERS O
        ON C.C_ID = O.C_IDsalessales
    GROUP BY C.SEGMENT
    HAVING COUNT(O.O_ID) > 1
    ORDER BY TOTAL_ORDERS DESC
    LIMIT 1;
END $$
DELIMITER ;
 CALL SEGMENT_ORDER_DETAIL();
 
 -- ______________Advanced SALES ANALYSIS _____________________________
 SELECT *FROM SALES;
SELECT ORDER_ID, COUNTRY,TOTAL_AMOUNT 
FROM SALES;
SELECT ORDER_ID, COUNTRY,REGION 
FROM SALES
WHERE REGION ='NORTH';
-- FIND ALL THE ORDERS SHIPPED VIA ECONOMY MODE WITH A TOTAL AMOUNT GREATER THAN 25000
SELECT  *FROM SALES
WHERE SHIP_MODE='ECONOMY' AND TOTAL_AMOUNT > 25000;

-- RETRIEVE ALL THE SALES DATA FOR TECHNOLOGY' CATEGORY IN IRELAND MADE AFTER 2020-01-01
SELECT *FROM SALES 
WHERE CATEGORY='TECHNOLOGY' AND COUNTRY='IRELAND' AND ORDER_DATE > '2020-01-01';

-- LIST THE TOP 10 PROFITABLE SALES TRANSACTIONS IN DESCENDING OREDR
SELECT *FROM SALES
ORDER BY UNIT_PROFIT DESC
LIMIT 10;

-- WILDCARD(%)
SELECT COUNTRY FROM SALES
WHERE COUNTRY LIKE 'AU%';

SELECT STATE FROM SALES
WHERE STATE LIKE '%N';

-- FIND ALL THE NAMES STARTS WITH 'J' AAND ENDS WITH 'N'
SELECT CUSTOMER_NAME FROM SALES
WHERE CUSTOMER_NAME LIKE 'J% %N';

SELECT PRODUCT_NAME FROM SALES
WHERE PRODUCT_NAME LIKE '%ACCO%';

-- GET THE TOP 5 CITIES WITH TOTAL AMOUNT
SELECT CITY,SUM(TOTAL_AMOUNT) AS TOTAL_SALES FROM SALES
GROUP BY CITY
ORDER BY TOTAL_SALES DESC
LIMIT 5;

-- DISPLAY THE  SECOND SET OF 10 RECORDS FOR CUSTOMER_NAME AND TOTAL_AMOUNT IN DECREASING ORDER
SELECT CUSTOMER_NAME,TOTAL_AMOUNT FROM SALES
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10,10;

-- FIND THE TOTAL REVENUE, AVERAGE UNIT COST AND TOTAL NUMBER OF ORDERS
SELECT SUM(TOTAL_AMOUNT) AS TOTAL,
       AVG(UNIT_COST) AS AVERAGE,
       COUNT(ORDER_ID) AS TOTAL_COUNT
FROM SALES;

-- count the unique no. of regions
SELECT COUNT(DISTINCT REGION) as unique_regions 
FROM SALES;

-- Get customers who have placed orders worth more than ₹50,000.
SELECT Customer_Name, SUM(Total_Amount) AS Total_Spent
FROM Sales
GROUP BY Customer_Name
HAVING SUM(Total_Amount) > 50000
ORDER BY Total_Spent DESC;

-- Rank products based on total sales using RANK().
SELECT Product_Name, SUM(Total_Amount) AS Total_Sales,
       RANK() OVER (ORDER BY SUM(Total_Amount) DESC) AS Sales_Rank
FROM Sales
GROUP BY Product_Name;

-- Find the top 5 customers by sales revenue using DENSE_RANK().
SELECT Customer_Name,
       SUM(Total_Amount) AS Total_Spent,
       DENSE_RANK() OVER (ORDER BY SUM(Total_Amount) DESC) AS Top_Rank
FROM Sales
GROUP BY Customer_Name
ORDER BY Top_Rank
LIMIT 5;

-- Use a CTE to find the top 3 most sold product categories.
WITH CategorySales AS (
    SELECT Category,
           SUM(Sold_Quantity) AS Total_Units,
           RANK() OVER (ORDER BY SUM(Sold_Quantity) DESC) AS category_rank
    FROM Sales
    GROUP BY Category
)
SELECT *
FROM CategorySales
WHERE category_rank <= 3;

SELECT * FROM SALES;


 







 




















  



 





       

      
